### ISSUE TITLE
Craft 3.4 RC3: Saving plugin settings crashes on project config

### ISSUE THREAD

**Issue by janhenckens** [nystudio107/craft3-imageoptimize#188]
On a site running Craft 3.4 RC3, when I try to change and save (or just save) the plugin's settings, the site crashes with the following error:

```
yii\base\ErrorException: array_key_exists() expects parameter 2 to be array, null given in /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php:1727
Stack trace:
#0 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/web/ErrorHandler.php(74): craft\web\ErrorHandler->handleError()
#1 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php(1727): craft\web\ErrorHandler->handleError()
#2 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php(1727): ::array_key_exists()
#3 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php(1597): craft\services\ProjectConfig->_loadInternalConfigData()
#4 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php(1586): craft\services\ProjectConfig->_getStoredConfig()
#5 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php(397): craft\services\ProjectConfig->_getLoadedConfig()
#6 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\services\ProjectConfig->get()
#7 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/base/ApplicationTrait.php(1333): craft\web\Application->_setTimeZone()
#8 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/web/Application.php(100): craft\web\Application->_preInit()
#9 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#10 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/base/Application.php(206): craft\web\Application->__construct()
#11 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/web/Application.php(91): craft\web\Application->__construct()
#12 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/di/Container.php(400): craft\web\Application->__construct()
#13 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs()
#14 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build()
#15 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#16 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject()
#17 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/bootstrap/web.php(51): ::unknown()
#18 /Users/jhenckens/Sites/okaweb/public/index.php(20): ::unknown()
#19 {main}
```

When saving settings for other plugins (SEOmatic, feed-me, freeform), the error doesn't present itself, so it appears to be something specific to this plugin.

Let me know if you need more information or need me to test something.

**Comment by khalwat** [comment]
The only thing I do "special" here is the use of Fields ->

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/models/Settings.php#L361

So that a subset of the actual model is what ends up being used/validated. Maybe Project Config doesn't like this standard Yii-ism, or I'm doing it wrong somehow?

**Comment by khalwat** [comment]
I filed this to make sure the Pixel & Tonic folks see it: https://github.com/craftcms/cms/issues/5483

...as I think it's _likely_ that this is an issue with changes in Project Config for Craft 3.4

**Comment by janhenckens** [comment]
Started creating an issue on the craftcms/cms too at first but since this is on the only plugin that's having the issue... I'll follow along there!

**Comment by khalwat** [comment]
I can't reproduce. Let's discuss in the P&T thread.
