### ISSUE TITLE
Asset replacement fails when used with Amazon S3 storage

### ISSUE THREAD

**Issue by TheFunkyMonk** [nystudio107/craft3-imageoptimize#253]
### Description
When ImageOptimize is used in conjunction with Craft's [Amazon S3](https://github.com/craftcms/aws-s3) plugin, trying to replace an existing asset always results in a failed optimization task in the queue and doesn't overwrite the existing image.

### To reproduce
Steps to reproduce the behaviour:
1. Set ImageOptimize to process an assets bucket using [Amazon S3](https://github.com/craftcms/aws-s3) (set up according to [this guide](https://nystudio107.com/blog/using-aws-s3-buckets-cloudfront-distribution-with-craft-cms)).
2. Upload an image asset
3. Try to replace uploaded asset with a new file under the same name and choose to Overwrite.
4. See "Failed" sidebar item for stuck optimization task.
 
### Expected behaviour
New asset uploads and overwrites the existing asset successfully.

### Versions
- Plugin version: ImageOptimize v1.6.21, Amazon S3 v1.2.11
- Craft version: v3.6.3

**Comment by joshuabaker** [comment]
This also impacts renaming, which under the hood is also a replacement (see [`rename` method](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/4e25cc0582a36a786c31115e419c6e40498f6972/src/AwsS3Adapter.php#L157-L164)).

**Comment by khalwat** [comment]
I'll take a look at this, but I'm a little confused...  because ImageOptimize just uses regular old Craft Transforms under the hood. So everything should work exactly the way it would work if you did this with regular Craft assets.

Can you please post the logs @TheFunkyMonk the show the errors that occur when this happens? It'll be in `queue.log` most likely, but possibly `web.log` too.

**Comment by TheFunkyMonk** [comment]
[queue.log](https://github.com/nystudio107/craft-imageoptimize/files/5961680/queue.log)
[web.log](https://github.com/nystudio107/craft-imageoptimize/files/5961683/web.log)

Here's the two logs, I stripped out everything prior to today and pulled them down right after reproducing the issue with an image called `puppy.jpg`.

I'm seeing some errors in `web.log` about `jpegoptim` not being available on the server (though responsive variants are still being generated) and this in `queue.log` that may be more relevant:

```
2021-02-10 13:24:20 [-][1][-][error][craft\queue\QueueLogBehavior::afterError]  [2711] Optimizing image id 27730 (attempt: 1) - Error (time: 25.794s): Call to a member function getVolume() on null
2021-02-10 13:24:20 [-][1][-][error][Error] Error: Call to a member function getVolume() on null in /srv/app/myappname/htdocs/vendor/craftcms/cms/src/services/AssetTransforms.php:763
```

**Comment by khalwat** [comment]
So these lines in the log:

```
2021-02-10 12:29:37 [-][11871][-][error][nystudio107\imageoptimize\services\Optimize::executeImageProcessor] /usr/bin/jpegoptim does not exist
``` 

Indicate that `jpegoptim` is not installed or it's not pointing to the right path. See here for how to install it and/or change the path: https://nystudio107.com/docs/image-optimize/Configuring.html#native-craft-images

As for the other issue, what I'm seeing is this:

```
2021-02-10 11:20:33 [-][11871][-][error][Error] Error: Call to a member function getVolume() on null in /srv/app/myappname/htdocs/vendor/craftcms/cms/src/services/AssetTransforms.php:763
Stack trace:
#0 /srv/app/myappname/htdocs/vendor/craftcms/cms/src/services/AssetTransforms.php(706): craft\services\AssetTransforms->_generateTransform(Object(craft\models\AssetTransformIndex))
#1 /srv/app/myappname/htdocs/vendor/craftcms/cms/src/services/Assets.php(626): craft\services\AssetTransforms->ensureTransformUrlByIndexModel(Object(craft\models\AssetTransformIndex))
#2 /srv/app/myappname/htdocs/vendor/nystudio107/craft-imageoptimize/src/imagetransforms/CraftImageTransform.php(65): craft\services\Assets->getAssetUrl(Object(craft\elements\Asset), Object(craft\models\AssetTransform), true)
#3 /srv/app/myappname/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(521): nystudio107\imageoptimize\imagetransforms\CraftImageTransform->getTransformUrl(Object(craft\elements\Asset), Object(craft\models\AssetTransform))
#4 /srv/app/myappname/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(130): nystudio107\imageoptimize\services\OptimizedImages->addVariantImageToModel(Object(craft\elements\Asset), Object(nystudio107\imageoptimize\models\OptimizedImage), Object(craft\models\AssetTransform), Array, 2.7801911381407)
#5 /srv/app/myappname/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(248): nystudio107\imageoptimize\services\OptimizedImages->populateOptimizedImageModel(Object(craft\elements\Asset), Array, Object(nystudio107\imageoptimize\models\OptimizedImage), false)
#6 /srv/app/myappname/htdocs/vendor/nystudio107/craft-imageoptimize/src/jobs/ResaveOptimizedImages.php(115): nystudio107\imageoptimize\services\OptimizedImages->updateOptimizedImageFieldData(Object(nystudio107\imageoptimize\fields\OptimizedImages), Object(craft\elements\Asset), false)
#7 /srv/app/myappname/htdocs/vendor/yiisoft/yii2-queue/src/Queue.php(246): nystudio107\imageoptimize\jobs\ResaveOptimizedImages->execute(Object(craft\queue\Queue))
#8 /srv/app/myappname/htdocs/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('2484', 'O:52:"nystudio1...', '300', 1)
#9 /srv/app/myappname/htdocs/vendor/craftcms/cms/src/queue/Queue.php(127): yii\queue\cli\Queue->handleMessage('2484', 'O:52:"nystudio1...', '300', 1)
#10 /srv/app/myappname/htdocs/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#11 [internal function]: craft\controllers\QueueController->actionRun()
#12 /srv/app/myappname/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /srv/app/myappname/htdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#14 /srv/app/myappname/htdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('run', Array)
#15 /srv/app/myappname/htdocs/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('run', Array)
#16 /srv/app/myappname/htdocs/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('queue/run', Array)
#17 /srv/app/myappname/htdocs/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('queue/run', Array)
#18 /srv/app/myappname/htdocs/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#19 /srv/app/myappname/htdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /srv/app/myappname/htdocs/web/index.php(22): yii\base\Application->run()
#21 {main}
2021-02-10 11:20:33 [-][11871][-][info][craft\queue\QueueLogBehavior::beforeExec]  [2485] Optimizing image id 27140 (attempt: 1) - Started
2021-02-10 11:20:33 [-][11871][-][info][craft\queue\QueueLogBehavior::afterExec]  [2485] Optimizing image id 27140 (attempt: 1) - Done (time: 0.001s)
2021-02-10 11:20:33 [-][11871][-][info][craft\queue\QueueLogBehavior::beforeExec]  [2486] Updating search indexes (attempt: 1) - Started
2021-02-10 11:20:33 [-][11871][-][info][craft\queue\QueueLogBehavior::afterExec]  [2486] Updating search indexes (attempt: 1) - Done (time: 0.001s)
2021-02-10 11:20:33 [-][11871][-][info][craft\queue\QueueLogBehavior::beforeExec]  [2487] Updating search indexes (attempt: 1) - Started
2021-02-10 11:20:33 [-][11871][-][info][craft\queue\QueueLogBehavior::afterExec]  [2487] Updating search indexes (attempt: 1) - Done (time: 0.024s)
2021-02-10 11:20:33 [-][11871][-][info][craft\queue\QueueLogBehavior::beforeExec]  [2488] Optimizing image id 27130 (attempt: 1) - Started
2021-02-10 11:20:33 [-][11871][-][info][nystudio107\imageoptimize\services\OptimizedImages::shouldCreateVariants] Array
```

It's an internal Craft CMS function that's throwing this error -- it appears to me that somehow, Asset ids `27140`, `27682`,  & `27730`  are not associated with any volume.

Can you look into these assets and your volume configuration to see what could be amiss here?

**Comment by khalwat** [comment]
Related? https://github.com/nystudio107/craft-imageoptimize/issues/255

**Comment by TheFunkyMonk** [comment]
@khalwat This got de-prioritized in our project (and sounds like it may actually be an issue with the S3 plugin) so I'm going to close for now. I'll open a new ticket if I'm able to repro in a more isolated environment and narrow it down, thanks for your help!
